# Week 2 - Data Analysis
#### Part 3
### Notebook created by Jonathan Penava
By the end of this lesson you should be able to read in a data set from a CSV file into a DataFrame, and manipulate that DataFrame.

## Overview
- NumPy
- Pandas
- <span style="color:red;">Data Frames</span>
- Reading CSV

## Data Frames

What is a dataframe?

A DataFrame is a 2 dimensional data structure (rows and columns).  These are similar to what you would see in SQL or Excel.  We will be using DataFrames to analize and manipulate our data sets.

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a','b','c']  
values1 = np.random.randint(1,20,4)
values2 = np.random.randint(1,20,4)   
values3 = np.random.randint(1,20,4)
cols = ['W','X', 'Y', 'Z']

In [5]:
multiArr = [values1.tolist(), values2.tolist(), values3.tolist()] #Converting the random integers into list using .tolist()

In [7]:
multiArr

[[11, 11, 13, 3], [13, 5, 2, 18], [19, 10, 11, 16]]

In [6]:
dataFrame = pd.DataFrame(data=multiArr, index=labels, columns=cols)
dataFrame

    W   X   Y   Z
a  11  11  13   3
b  13   5   2  18
c  19  10  11  16

In [12]:
dataFrame['X']    #This produces a Pandas Series
                  #[] displays int64 DataType

a    11
b     5
c    10
Name: X, dtype: int64

In [13]:
dataFrame[['X','Y']]  #This produces a DataFrame
                      #[[]] gives you the DataFrame Type

    X   Y
a  11  13
b   5   2
c  10  11

In [14]:
dataFrame.Z

a     3
b    18
c    16
Name: Z, dtype: int64

We can create new columns as we need them. We can also base the values in this column on other columns.

In [31]:
dataFrame['Sum(X+Y)']=dataFrame['X']+dataFrame['Y']     #Adding a new column into the dataframe.
dataFrame

    W   X   Y   Z  Sum(X+Y)
a  11  11  13   3        24
b  13   5   2  18         7
c  19  10  11  16        21

<ul>
<li>inplace=True is needed to make the change permanent.</li>
<li>For axis, row=0 and columns=1   Since we wanted to remove the Sum column we set axis to 1</li>
</ul>

In [ ]:
dataFrame.drop('Sum(X+Y)', axis=1, inplace=True) 
dataFrame
#Removing a column permanently.

    W   X   Y   Z
a  11  11  13   3
b  13   5   2  18
c  19  10  11  16

We can also add rows to our DataFrame if we wish.

In [33]:
row = [1, 2, 3, 4]
df2 = pd.DataFrame([row], columns=['W','X','Y','Z'], index=['d'])
dataFrame=pd.concat([dataFrame, df2])
dataFrame

#Adding Rows into the DataFrame.

    W   X   Y   Z
a  11  11  13   3
b  13   5   2  18
c  19  10  11  16
d   1   2   3   4